name=TFT_eSPI_ESP8266
version=1.0.0
author=Bodmer
maintainer=Bodmer
sentence=SPI TFT graphics library for ESP8266 boards with ST7789 displays
paragraph=Arduino graphics library for ESP8266 with SPI and ST7789 support.
category=Display
url=https://github.com/Diaszano/TFT_eSPI_ESP8266
architectures=esp8266
includes=TFT_eSPI.h
