#!/usr/bin/env python3
"""Convert an uncompressed indexed 4-bit BMP to palette and pixel C arrays."""
import argparse
import struct
import sys
from pathlib import Path


def convert(contents: bytes) -> str:
    if len(contents) < 54 or contents[:2] != b"BM":
        raise ValueError("not a supported BMP file")
    file_size, _, _, offset = struct.unpack_from("<IHHI", contents, 2)
    dib_size = struct.unpack_from("<I", contents, 14)[0]
    if dib_size < 40 or 14 + dib_size > len(contents):
        raise ValueError("unsupported or truncated BMP header")
    width, height, planes, bpp, compression, image_size, _, _, colors_used, _ = struct.unpack_from("<iiHHIIiiII", contents, 18)
    if width <= 0 or height <= 0 or planes != 1 or bpp != 4 or compression != 0:
        raise ValueError("expected positive-size, bottom-up, uncompressed 4-bit BMP")
    colors = colors_used or 16
    if colors > 16:
        raise ValueError("4-bit BMP palette cannot exceed 16 colors")
    palette_start = 14 + dib_size
    palette_end = palette_start + colors * 4
    if palette_end > len(contents) or offset < palette_end or offset > len(contents):
        raise ValueError("BMP palette or pixel offset is outside the file")
    stride = ((width * bpp + 31) // 32) * 4
    required = stride * height
    if (image_size and image_size < required) or offset + required > len(contents) or (file_size and file_size < offset + required):
        raise ValueError("BMP pixel data is truncated")

    palette = []
    for index in range(colors):
        blue, green, red, _ = struct.unpack_from("<4B", contents, palette_start + index * 4)
        palette.append(((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3))

    palette.extend([0] * (16 - colors))

    row_bytes = (width + 1) // 2
    pixels = []
    for row in range(height - 1, -1, -1):
        start = offset + row * stride
        row_pixels = contents[start:start + row_bytes]
        for column in range(width):
            packed = row_pixels[column // 2]
            index = (packed >> 4) if column % 2 == 0 else (packed & 0x0F)
            if index >= colors:
                raise ValueError("BMP pixel index is outside the palette")
        pixels.extend(row_pixels)

    output = "/* Generated by bmp2array4bit.py. */\n"
    output += f"static const uint16_t palette[16] = {{\n\t"
    output += ", ".join(f"0x{color:04x}" for color in palette)
    output += "\n};\n\n"
    output += f"// width is {width}, height is {height}\n"
    output += f"static const uint8_t myGraphic[{len(pixels)}] PROGMEM = {{\n\t"
    output += ", ".join(f"0x{value:02x}" for value in pixels)
    output += "\n};\n"
    return output


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-v", "--verbose", action="store_true", help="print conversion details")
    parser.add_argument("input", help="input BMP file")
    parser.add_argument("-o", "--output", help="output C file (default: input name with .c)")
    args = parser.parse_args(argv)
    source = Path(args.input)
    output = Path(args.output) if args.output else source.with_suffix(".c")
    try:
        generated = convert(source.read_bytes())
    except (OSError, ValueError, struct.error) as error:
        print(f"could not convert {source}: {error}", file=sys.stderr)
        return 1
    try:
        output.write_text(generated, encoding="utf-8")
    except OSError as error:
        print(f"could not write output file {output}: {error}", file=sys.stderr)
        return 1
    if args.verbose:
        print(f"converted {source} to {output}")
    else:
        print(f"Completed; the output is in {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
